# When master is updated, runs a docker build
# and pushes a docker image to Github registry
name: Build Docker Container
on:
  push:
    branches:
      - master
jobs:
  build:
    env:
      IS_MASTER_BUILD: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 23
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 23
#          Before tests can pass, need to set up DB, schema & test data
#      - name: Run tests
#        run: cd webapp; ./gradlew test
      - name: Login to GitHub Container Registry
        if: ${{ env.IS_MASTER_BUILD }}
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: build docker container
        if: ${{ env.IS_MASTER_BUILD }}
        run: |
          docker build schema/ --tag ghcr.io/wnc-supply-sites/wnc-supply-sites/flyway:latest
          docker push ghcr.io/wnc-supply-sites/wnc-supply-sites/flyway:latest

          cd webapp;

          ./gradlew clean bootJar
          docker build . --tag ghcr.io/wnc-supply-sites/wnc-supply-sites/webapp:latest
          docker push ghcr.io/wnc-supply-sites/wnc-supply-sites/webapp:latest
